# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-PathRequest
version:      1.18
version_from: lib/CGI/PathRequest.pm
installdirs:  site
requires:
    CGI:                           0
    Cwd:                           0
    File::MMagic:                  0
    File::PathInfo:                0
    Time::Format:                  0
    Want:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
