# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-PathRequest
version:      1.08
version_from: lib/CGI/PathRequest.pm
installdirs:  site
requires:
    CGI:                           3.00
    Cwd:                           3.01
    File::Type:                    0.22
    Time::Format:                  2.22
    Want:                          0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
