--- #YAML:1.0
name:               CGI-PathRequest
version:            1.19
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1
    CGI:                  3
    Cwd:                  3
    File::MMagic:         1.27
    File::PathInfo::Ext:  1.27
    HTML::Entities:       1.35
    Smart::Comments:      1
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
