# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-PathRequest
version:      1.16
version_from: lib/CGI/PathRequest.pm
installdirs:  site
requires:
    CGI:                           3
    Cwd:                           3
    File::MMagic:                  1
    File::PathInfo:                1.07
    Time::Format:                  1
    Want:                          0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
